version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cards_db_container
    environment:
      POSTGRES_DB: cards_db
      POSTGRES_USER: #######
      POSTGRES_PASSWORD: ######
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot_app
    ports:
      - "12009:12009"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cards_db
      SPRING_DATASOURCE_USERNAME: ########
      SPRING_DATASOURCE_PASSWORD: ########

volumes:
  pgdata:
